name: Sandbox

on: [workflow_dispatch, push, pull_request]

jobs:

  canary-multi-turn:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        model:
          - ibm-granite/granite-4.0-h-micro              # $0.0170/$0.1100 [ 128K]
    steps:
      - uses: actions/checkout@v4

      - run: ./chat-llm.js tests/en/canary-single-turn.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - run: ./chat-llm.js tests/en/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Uncommitted changes detected after running tests"
            git status --porcelain
            exit 1
          fi

  high-school-stem:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        model:
          - ibm-granite/granite-4.0-h-micro              # $0.0170/$0.1100 [ 128K]
    steps:
      - uses: actions/checkout@v4
      - run: ./chat-llm.js tests/en/high-school-stem.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Uncommitted changes detected after running tests"
            git status --porcelain
            exit 1
          fi

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        model:
          - ibm-granite/granite-4.0-h-micro              # $0.0170/$0.1100 [ 128K]
    steps:
      - uses: actions/checkout@v4
      - run: ./chat-llm.js tests/en/general-knowledge.txt
        env:
          LLM_API_BASE_URL: https://openrouter.ai/api/v1
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Uncommitted changes detected after running tests"
            git status --porcelain
            exit 1
          fi